name: plade
description: A type-safe command-line parsing library
version: 0.1.0
homepage: https://github.com/refi64/plade

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.5
